[build-system]
requires = [
  "setuptools>=64",
  "wheel",
  "torch-npu==2.7.1",
  "torch==2.7.1",
  "pandas",
  "datasets",
]
build-backend = "setuptools.build_meta"

[project]
name = "dynamicPD"
version = "0.11.0"
requires-python = ">=3.10"
description = "dynamicPD adapt vllm"

[project.entry-points."vllm.general_plugins"]
dynamicPD = "dynamicPD.plugin:dynamicPD_plugin"

[project.optional-dependencies]
vllm = [
  "vllm==0.11.0",
]
vllm-ascend = [
  "vllm-ascend==0.11.0"
]

[tool.setuptools.packages.find]
include = ["dynamicPD*"]
